package model.pojos;
// Generated ago 5, 2017 7:19:54 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Docentes generated by hbm2java
 */
public class Docentes  implements java.io.Serializable {


     private String codDocente;
     private String codEstudiante;
     private String administrador;
     private String nombre;
     private String apellido;
     private int cedula;
     private String directorA;
     private String sexo;
     private int anoLectivo;

    public Docentes() {
    }
    

	
    public Docentes(String codDocente) {
        this.codDocente = codDocente;
    }
    public Docentes(String codDocente, String codEstudiante, String administrador, String nombre, String apellido, int cedula, String directorA, String sexo, int anoLectivo) {
       this.codDocente = codDocente;
       this.codEstudiante = codEstudiante;
       this.administrador = administrador;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.directorA = directorA;
       this.sexo = sexo;
       this.anoLectivo = anoLectivo;
    }
   
    public String getCodDocente() {
        return this.codDocente;
    }
    
    public void setCodDocente(String codDocente) {
        this.codDocente = codDocente;
    }
    public String getCodEstudiante() {
        return this.codEstudiante;
    }
    
    public void setCodEstudiante(String codEstudiante) {
        this.codEstudiante = codEstudiante;
    }
    public String getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(String administrador) {
        this.administrador = administrador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getDirectorA() {
        return this.directorA;
    }
    
    public void setDirectorA(String directorA) {
        this.directorA = directorA;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getAnoLectivo() {
        return this.anoLectivo;
    }
    
    public void setAnoLectivo(int anoLectivo) {
        this.anoLectivo = anoLectivo;
    }




}


