package model.pojos;
// Generated ago 5, 2017 7:19:54 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private String codEstudiante;
     private int cedula;
     private String nombre;
     private String apellido;
     private int grado;
     private String sexo;
     private String paralelo;
     private Date fechaMatricula;
     private int anoLectivo;

    public Estudiantes() {
    }

	
    public Estudiantes(String codEstudiante) {
        this.codEstudiante = codEstudiante;
    }
    public Estudiantes(String codEstudiante, int cedula, String nombre, String apellido, int grado, String sexo, String paralelo, Date fechaMatricula, int anoLectivo) {
       this.codEstudiante = codEstudiante;
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellido = apellido;
       this.grado = grado;
       this.sexo = sexo;
       this.paralelo = paralelo;
       this.fechaMatricula = fechaMatricula;
       this.anoLectivo = anoLectivo;
    }

    
    public String getCodEstudiante() {
        return this.codEstudiante;
    }
    
    public void setCodEstudiante(String codEstudiante) {
        this.codEstudiante = codEstudiante;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getGrado() {
        return this.grado;
    }
    
    public void setGrado(int grado) {
        this.grado = grado;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public int getAnoLectivo() {
        return this.anoLectivo;
    }
    
    public void setAnoLectivo(int anoLectivo) {
        this.anoLectivo = anoLectivo;
    }




}


